name = "meet-us"
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

assets = { directory = "./public" }

[vars]
BETTER_AUTH_URL = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "meet-us-db"
database_id = "19eb4a88-f170-4f6c-bf7b-7e8ad925ded3"
migrations_dir = "drizzle/migrations"
